presidents/pages/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^president/(?P<slug>[A-Za-z\s\-_]+)/$', views.president_profile, name='pres_profile'),

]

presidents/presidents/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from api import views as apiviews
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'presidents', apiviews.PresidentViewSet)
router.register(r'speeches', apiviews.SpeechViewSet)


urlpatterns = [

    # Django Admin
    url(r'^admin/', admin.site.urls),

    # Public Front End PAges
    url(r'', include('pages.urls', namespace='pages')),

    # REST API
    url(r'^api/v1/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

presidents/profiles/models.py
from __future__ import unicode_literals
from django.db import models
import datetime
from django.utils.text import slugify
from readability.ari import ari_score
from tf_idf.importance import score_corpus
from language.models import WordTag

from tf_idf.similarity import similarity_vectorizer
from gensim.summarization import summarize as gsummarize



class Person(models.Model):
    first_name = models.CharField(max_length=500, blank=True, null=True)
    middle_name = models.CharField(max_length=500, blank=True, null=True)
    last_name = models.CharField(max_length=500, blank=True, null=True)
    slug = models.SlugField(null=True, blank=True, editable=False)
    common_name = models.CharField(max_length=500, blank=True, null=True)
    gender = models.CharField(max_length=500, blank=True, null=True)  # Keep as CharField
    birth_location = models.CharField(max_length=1024, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    deceased_date = models.DateField(blank=True, null=True)
    death_location = models.CharField(max_length=1024, blank=True, null=True)
    education = models.CharField(max_length=1024, blank=True, null=True)
    lifespan = models.PositiveSmallIntegerField(blank=True, null=True)
    age = models.PositiveSmallIntegerField(blank=True, null=True, editable=False)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        """
        Assures that each Person's full name is unique. There can only be one!
        """
        unique_together = ('first_name', 'middle_name', 'last_name')
        # sets the plural of person to people
        verbose_name_plural = 'people'
        # describe how you want this to be ordered in the database
        ordering = ['-birth_date']  # order by reverse birth dates

    def save(self, *args, **kwargs):
        self.slug = slugify(self.common_name)
        self.set_age()
        super().save(*args, **kwargs)

    def __str__(self):
        names = " ".join([self.first_name, self.middle_name, self.last_name])
        return names

    def set_age(self):
        """
        Calculates and returns either the age or the years lived of the person
        """
        if self.birth_date and self.deceased_date:
            # gets the difference as a timedelta objects
            delta = self.deceased_date - self.birth_date
            # gets the days of the timedelta and converts to years
            self.lifespan = delta.days // 365

        if self.birth_date:
            delta = datetime.datetime.now().date() - self.birth_date
            self.age = delta.days // 365


class President(Person):
    REASONS = (
        ('NSR', 'Did Not Seek Re-election'),
        ('TME', 'Term Ended'),
        ('LRE', 'Lost'),
        ('DIO', 'Died in Office'),
        ('ASN', 'Assassinated'),
        ('RSG', 'Resigned'),
        ('IPH', 'Impeached'),
    )
    elections_won = models.PositiveSmallIntegerField(default=0)
    presidency_number = models.PositiveSmallIntegerField(blank=True, null=True)
    party = models.CharField(max_length=200, blank=True, null=True)
    start_year = models.DateTimeField(blank=True, null=True)
    end_year = models.DateTimeField(blank=True, null=True)
    reason_left_office = models.CharField(max_length=3, choices=REASONS, blank=True, null=True)
    wordcloud = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.common_name


class SpeechSimilarity(models.Model):
    source = models.ForeignKey('Speech', related_name='similar')
    target = models.ForeignKey('Speech', related_name='popular')
    score = models.FloatField()

    class Meta:
        ordering = ['source__speaker__common_name', '-score']

    def __str__(self):
        return f'{self.score} {self.source.pk}<->{self.target.pk}'



class Speech(models.Model):
    speaker = models.ForeignKey(President, related_name='speeches')
    title = models.CharField(max_length=1024, blank=True, null=True, unique=True)
    slug = models.SlugField(max_length=1024, blank=True, null=True, editable=False)
    url = models.URLField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    body = models.TextField()
    summary = models.TextField(blank=True, null=True)
    ARI_score = models.PositiveSmallIntegerField(default=0)
    ARI_display = models.CharField(max_length=100, default="Not Scored Yet.")
    similar_speeches = models.ManyToManyField('self', through='SpeechSimilarity', symmetrical=False)

    class Meta:
        unique_together = ['speaker', 'title', 'date']
        ordering = ['-date', 'speaker']

    def save(self, refresh=True, *args, **kwargs):

        self.slug = slugify(self.title)

        if refresh:
            score, scoredata = ari_score(self.body)
            self.ARI_score = score
            self.ARI_display = scoredata['grade_level']
            self.tag_tfidf()

        super().save(*args, **kwargs)

    def tag_tfidf(self, everybody=False, quantity=25):
        if everybody:
            all_speeches_corpus = Speech.objects.all().values_list('body', flat=True)
            corpus = all_speeches_corpus
        else:
            presidential_corpus = self.speaker.speeches.all().values_list('body', flat=True)
            corpus = presidential_corpus

        speech = self.body
        word_scores = score_corpus(speech, corpus)

        for word, score in word_scores[:quantity]:
            tag, created = WordTag.objects.get_or_create(corpus=self, word=word, score=score, method='TFIDF')
            if created:
                tag.save()
        return word_scores


    def get_similar_speeches(self, quantity=10, set=False):

        all_speeches_corpus = iter(Speech.objects.values_list('pk', 'body'))
        similar = similarity_vectorizer(self.body, all_speeches_corpus)                     # Generator

        result = sorted(similar, key=lambda t: t[1], reverse=True)[:quantity]               # Consume

        if set:
            for pk, score in result:
                if pk == self.pk:
                    continue

                similarity, created = SpeechSimilarity.objects.update_or_create(source=self, target_id=int(pk),
                                                                                defaults={'score':score})
                similarity.save()
        else:
            return result

    def summarize(self, set=False):
        summary = gsummarize(self.body, word_count=100)
        if set:
            self.summary = summary
            self.save(refresh=False)
            return

        return summary


    def __str__(self):
        return '{} by {}'.format(self.title, self.speaker.common_name)


    def __len__(self):
        return len(self.body)

presidents/pages/templates/pages/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Presidents</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'pages/css/fonts.css' %}">
</head>

<body>

    {% include 'pages/nav.html' %}

    <main class="container">
        {% block main %}
        {% endblock %}
    </main>

    <footer class="footer text-center">
        {% block footer %}
        {% endblock %}
        <credit class="credit">
            <span class="red-text">★</span> Kieran R Prasch | Gabrielle Simard-Moore <span class="red-text">★</span>
        </credit>
    </footer>

</body>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/presidents.js' %}"></script>

{% block scripts %}
{% endblock %}

</html>

presidents/pages/templates/pages/home.html
{% extends 'pages/base.html' %}

{% block main %}

    {#            Banner           #}
    <section class="container-fluid">
        <div id="president-banner" class="us-101 banner row text-center">
            <h1> ★ <span class="red-text">{{ num_presidents }} </span> U.S. Presidents ★</h1>
            <h4>
                <span>------------------------------------</span>
                <span class="declaration"><span class="blue-text">{{ num_speeches }}</span>
                    Speeches</span>
                <span>------------------------------------</span>
            </h4>
        </div>
    </section>
    <hr/>
    {#end Banner#}

    {% include 'pages/presidents_list.html' %}

{% endblock %}

presidents/pages/templates/pages/nav.html
  <div class="container">

    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">About</a></li>
        <li><a href="/presidents">Presidents</a></li>
        <li><a href="/speeches/">Speeches</a></li>
      </ul>
    </div><!--/.nav-collapse -->

  </div>

presidents/pages/templates/pages/president_detail.html
{% extends 'pages/base.html' %}

{% block main %}
    <section id="flex-parent">
        <div class="big-star text-center">
            <div>
                <span class="president-name us-101 white-text">{{ president.common_name }}</span>
            </div>
            <div class="">
                <span class="president-term white-text declaration">
                    {{ president.start_year|date:"Y" }} - {{ president.end_year|date:"Y" }}
                </span>
            </div>
        </div>
    </section>

    <section class="container">

        <div class="speech-list">
          <table class='table table-striped'>
              {% for speech in speeches %}
                  <tr><td><a href="/speeches/{{ speech.id }}">{{ speech }}</a></td></tr>
              {% endfor %}
          </table>
        </div>


    </section>


{% endblock %}

presidents/pages/templates/pages/presidents_list.html
{#{% extends 'pages/base.html' %}#}
{##}
{#{% block main %}#}

<section id='presidents-datatable' class='container'>

  <table class="table">

      <thead>
          <tr>
              <td> Presidency </td>
              <td> Dates </td>
              <td> Common Name </td>
              <td> Speeches Available </td>
              <td> Reson for leaving Office </td>
              <td> ARI Score </td>
              <td> Birth Location</td>
          </tr>
      </thead>

      {% for president in presidents %}
        <tr>
          <td> {{ president.presidency_number }} </td>
          <td> {{ president.start_year|date:"M d, Y" }} - {{ president.end_year|date:"M d, Y" }} </td>
          <td> <a href="/presidents/{{president.slug}}">{{ president.common_name }}<a> </td>
          <td> {{ president.speeches.all|length }} </td>
          <td> {{ president.get_reason_left_office_display }} </td>
          <td> {{ president.ari_score }} </td>
          <td> {{ president.birth_location }} </td>
        </tr>
      {% endfor %}

    </table>

</section>

{#{% endblock %}#}

presidents/pages/templates/pages/speech_detail.html
{% extends 'pages/base.html' %}

{% block main %}

<section class="container">

    <div class="well">
      <h1>{{ object }}</h1>
      {{ object.date|date:"M d, Y" }}
      <article class="text-left">
        {{ object.body }}
      </article>

    <div>

</section>

{% endblock %}

presidents/pages/templates/pages/speech_list.html
{% extends 'pages/base.html' %}

{% block main %}

<section class="container">


    <div>

       <div class="panel panel-default">
         <div class="panel-heading">
            <h1><span id="speech-count">{{ speeches|length }} Total</span> Speeches</h1>
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1t"></span>
              <input type="text" data-toggle="popover" title="Transcript Search"
                     data-content="Searches against transcript keywords and meta data."
                     data-placement="bottom" id="search"
                     class="form-control" placeholder="keywords"
                     aria-describedby="basic-addon1">
            </div>

           </div>
         <div class="panel-body">
            <table class='table table-striped'>
                {% for speech in speeches %}
                    <tr data-id="{{ speech.id }}">
                      <td>{{ speech.date|date:"M d, Y" }}</td>
                      <td><a href="/speeches/{{ speech.id }}/">{{ speech }}</a></td>
                    </tr>
                {% endfor %}
            </table>
          </div>
    </div>
    </div>

    {# .... **Now the pagination section** .... #}
    {% if is_paginated %}
        <nav class="pagination">
            <ul class="pagination">
              <li>
                {% if page_obj.has_previous %}
                    <a href="/speeches?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="/speeches?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
              </li>
            </ul>
        </nav>
    {% endif %}

</section>

{% endblock %}